# Generated by Django 5.2.1 on 2025-05-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
