# Generated by Django 5.2.1 on 2025-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
